version: "3.9"
services:
  web:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=flask_twitter_clone:create_app
      - FLASK_ENV=development
  db:
    image: postgres:14
    container_name: pg_container
    environment:
      POSTGRES_DB: twitter_clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
